import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto flex justify-center items-center py-10">
          <Image
            src={`/fm_logo.png`}
            alt="fm_logo"
            width={100}
            height={100}
            className="aspect-ratio"
          />
        </div>
        {children}
      </body>
    </html>
  );
}
